config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :bakeries do
    resources :reviews, only: [:new, :create]
    resources :tags, only: [:new, :create, :update]
  end
  get 'bakeries/addtofav/:id', to: "bakeries#update_favourites"

  resources :users
  get 'users/:id/favourites', to: "users#favourites"
  resources :favourites
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bakery.rb
class Bakery < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :tags, dependent: :destroy
  belongs_to :user
  has_many_attached :pictures
  geocoded_by :address
  after_validation :geocode

  include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [ :name],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :bakery

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :bakery
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :bakery
  has_one_attached :photo
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :bakery
  has_many :user_tags, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bakeries, dependent: :destroy
  has_many :user_tags, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favourites, dependent: :destroy
end

app/models/user_tag.rb
class UserTag < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @bakeries = current_user.favourites.map{|fav| fav.bakery}
    test = Bakery.where(id: @bakeries.pluck(:id))
    @markers = test.geocoded.map do |bakery|
      {
        lat: bakery.latitude,
        lng: bakery.longitude,
        image_url: helpers.asset_url('baguette2.png'),
        info_window: render_to_string(partial: "../views//bakeries/info_window", locals: { bakery: bakery })
      }
    end

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end
  def create
    @bakery = Bakery.find(params[:bakery_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.bakery = @bakery
    if @review.save
      respond_to do |format|
      format.html { redirect_to bakery_path(@bakery) }
      format.text { render partial: 'reviews/reviews', locals: { review: @review }, formats: [:html] }
      end
    end
  end
  private

def review_params
  params.require(:review).permit(:content, :title,:visitor,:rating,:photo)
end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
   skip_before_action :verify_authenticity_token, :only => [:update]

  def new
      @tag = Tag.new
  end
  def create
    @bakery = Bakery.find(params[:bakery_id])
    @tag = Tag.new(tag_params)
    @tag.bakery = @bakery
    @user_tag = UserTag.create(user: current_user, tag: @tag)
    if (@tag.save && @user_tag.save)
      respond_to do |format|
      format.html { redirect_to bakery_path(@bakery) }
      format.text { render partial: 'bakeries/tag', locals: { tag: @tag }, formats: [:html] }
      end
    end
  end

  def update
    @bakery = Bakery.find(params[:bakery_id])
    @tag = Tag.find(params[:id])
    @verify_user_tag = UserTag.where(tag: @tag).where(user: current_user)
    if @verify_user_tag.empty?
      @user_tag = UserTag.new(user: current_user, tag: @tag)
      if @user_tag.save
        respond_to do |format|
          format.html { redirect_to bakery_path(@bakery) }
          format.text { render partial: 'bakeries/tag', locals: { tag: @tag }, formats: [:html] }
        end
      end
    else
      respond_to do |format|
          format.html { redirect_to bakery_path(@bakery) }
          format.text { render partial: 'bakeries/tag', locals: { tag: @tag }, formats: [:html] }
        end

    end
  end

  private

  def tag_params
    params.require(:tag).permit(:category)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @favourites = Favourite.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bakeries/_favourites.html.erb
  <div data-refresh-list-target='id' data-id="<%= bakery.id %>" >
    <% favourite = Favourite.find_by(user: current_user, bakery: bakery) %>
    <% if favourite.nil? %>
      <%= link_to "", bakery_favourites_path(bakery), method: :create, class:"far fa-star fa-lg favourite-icon" %>

    <%else %>
      <%= link_to "", favourite_path(favourite), method: :delete, class:"fa fa-star fa-lg favourite-icon" %>
    <%end %>
  </div>

app/views/bakeries/_info_window.html.erb
<div class ='fit' data-lat=<%=bakery.latitude %> data-lng=<%=bakery.longitude %>>
  <% if bakery.pictures.attached? %>
   <%= cl_image_tag bakery.pictures[0].key, height: 100, width: 150, crop: :fill %>
  <%else %>
    <img id="imgProd1" src="https://picsum.photos/id/237/200/150">
  <% end %>
  <div class='name'><%= link_to bakery.name.upcase,bakery_path(bakery) %></div>
  <div class='address'><%= bakery.address %></div>


  <% if (Time.now.hour > bakery.opening_hour.hour && Time.now.hour < bakery.closing_hour.hour)%>
    <p class='schedule' style="color:green">Open</p><button class='btn show-tag'>Take me here</button>
  <%else %>
    <p class='schedule' style="color:red">Closed </p><button class='btn show-tag'>Take me here</button>
  <%end %>
</div>

app/views/bakeries/_list.html.erb
<div >
  <%unless @bakeries.empty? %>

      <% @bakeries.each do |bakery| %>
        <div class="bakery-card fit shadow mb-3 bg-white rounded d-flex" data-refresh-list-target="list" data-lat=<%=bakery.latitude %> data-lng=<%=bakery.longitude %>>
          <% if bakery.pictures.attached? %>

              <%= cl_image_tag bakery.pictures.first.key, height: 200, width: 158, crop: :fill %>
          <%else %>
            <img id="imgProd1" src="https://picsum.photos/id/237/158/150">
          <% end %>

          <div class="bakery-card-infos p-2">

            <div id="name" class="bakery_name">
              <h4><%= link_to bakery.name.upcase,bakery_path(bakery) %></h4>
            </div>

            <div id="address">
              <p><%= bakery.address.capitalize %>, <%= bakery.post_code %></p>
            </div>

            <div id="location" class='pt-2'>
              <div>
                <p class= 'ranking'><%= "##{bakery.rank.to_i + 1} IN BELGIUM" %></p>
              </div>
            </div>

          </div>

          <div class='extras d-flex justify-content-between'>
            <div class='p-2 d-flex flex-column justify-content-between'>
              <div id="time">
                <% if (Time.now.hour > bakery.opening_hour.hour && Time.now.hour < bakery.closing_hour.hour)%>
                  <p style="color:green">Open</p>
                <%else %>
                  <p style="color:red">Closed </p>
                <%end %>
              </div>
              <div class="distance-p">
                <%= link_to bakery_path(bakery) do %>
                 Learn more
                  <i class="fas fa-arrow-right"></i>
                <% end %>
              </div>
            </div>
            <div class='p-2 d-flex flex-column justify-content-between' data-controller="refresh-list">
                <%= render '/bakeries/favourites', bakery: bakery, class: "favourites" %>
            </div>

          </div>
        </div>

      <% end %>

      <%else %>
        <h1>No bakeries found!</h1>
      <%end %>
</div>

app/views/bakeries/_modal.html.erb
<div data-controller='modal'>
<!-- Button trigger modal -->
 <% if @bakery.pictures.attached? %>
      <%= cl_image_tag @bakery.pictures.first.key, crop: :fill %>
  <%else %>
   <button class='picture'><img   src="https://picsum.photos/id/237/400/500" data-modal-target='button' data-action="click->modal#displayModal" data-toggle="modal" data-target="#exampleModal"></button>
  <% end %>
<!-- Modal -->
<div class="modal fade"  data-modal-target='modal' id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" data-modal-target='close'data-action="click->modal#closeModal" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" data-modal-target='picList'>
          <% if @bakery.pictures.attached? %>
            <%@bakery.pictures.each do |picture| %>
              <div class="carousel-item active">
                <%= cl_image_tag picture.key, crop: :fill ,class:"d-block caroussel-pic" ,alt:'picture' %>
              </div>
              <%end %>
          <%else %>
            <div class="carousel-item active">
              <img class="d-block caroussel-pic" src="https://www.sortiraparis.com/images/80/93419/629767-leonie-bakery-boulangerie-de-quartier-aux-batignolles.jpg" alt="First slide">
            </div>
            <div class="carousel-item ">
              <img class="d-block caroussel-pic" src="https://res.cloudinary.com/tf-lab/image/upload/w_600,h_337,c_fill,g_auto:subject,q_auto,f_auto/restaurant/83653502-099e-4508-beb2-5617d5263d0e/5bb815ec-5a72-419a-b824-82797d09e9c0.jpg" alt="Second slide">
            </div>
            <div class="carousel-item ">
              <img class="d-block caroussel-pic" src="https://media-exp1.licdn.com/dms/image/C511BAQEQyNIDOFug3w/company-background_10000/0/1519801426291?e=2147483647&v=beta&t=82QOknaGVP6fqt75L8v6GuhOYxCD0lrPY0bt14D4ZNY" alt="forth slide">
            </div>
            <div class="carousel-item ">
              <img class="d-block caroussel-pic" src="https://tableplacechairs.com/wp-content/uploads/2021/08/GAILS-BAKERY-TWICKENHAM-LONDON-for-web-7.jpg" alt="Third slide">
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev"  data-modal-target='picRight'role="button" data-action="click->modal#previous" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </button>
        <button class="carousel-control-next" data-modal-target='picLeft' role="button" data-action="click->modal#next" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </button>
      </div>
    </div>
  </div>
</div>

</div>

app/views/bakeries/_tag.html.erb
<div class='show-tag' data-controller='change-tag' data-change-tag-target='tagdiv' data-url=<%= bakery_tag_path(@bakery,tag)%> >
  <button class='btn' data-change-tag-target='tag' data-bakery=<%= @bakery.id %> data-id=<%= tag.id %> data-action='click->change-tag#addVote'  ><%= tag.category %> &nbsp;+<%=tag.user_tags.count  %></button>
</div>

app/views/bakeries/index.html.erb
<div id="index-container" >

  <!-- Below is the div that just is a 2 column grid for all pets on left and
  the map on the right-->
  <div class="parent d-flex">

    <!-- Below is the left column which contains all the pets -->
    <div class="bakery-cards col-6 p-3"  data-index-page-target='list'>
      <% unless @page.nil? %>
        <%= render 'list', bakeries: @bakeries %>

      <%else %>
      <%= render 'list', bakeries: @bakeries ,pictures:@pictures %>

      <% end %>

    </div>


    <!-- Below is the right column with the map -->

    <div class="map_card col-6 mb-3" id="map"
        style=" height: 92vh;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

  </div>
  <div id="myDIV"class ='d-flex'>
      <% if @bakeries_count %>
          <%unless @bakeries_count < 5 %>
          <%(@bakeries_count.to_f / 5).ceil.times do |time| %>
          <% if (time + 1) == @page.to_i %>
            <%= button_to (time+1) , bakeries_path, method: :get,class:'btn btn-page active', params: { button: (time+1) } %>
          <%else %>
            <%= button_to (time+1) , bakeries_path, method: :get,class:'btn btn-page', params: { button: (time+1) } %>
          <% end %>
          <%end %>
        <%end %>
      <% end %>

    </div>
</div>

app/views/bakeries/new.html.erb
<h2 class="form-title justify-content-center">Add a new bakery</h2>

<div class="form-to-add-a-bakery">

  <%= simple_form_for @bakery do |f| %>
    <div class= "content">
      <%= f.input :name, input_html:{class:"input-bakery"}, placeholder:"type your name" %>
      <%= f.input :phone_number, input_html:{class:"input-bakery"}, placeholder:"type your phone number" %>
      <%= f.input :address, input_html:{class:"input-bakery"}, placeholder:"type your address" %>

      <%= f.input :post_code, input_html:{class:"input-bakery"}, placeholder:"type your postcode" %>
      <%= f.input :opening_hour, input_html:{class:"input-bakery-hour"} %>
      <%= f.input :closing_hour, input_html:{class:"input-bakery-hour"} %>

      <%= f.input :description, label_html:{ class:"description-label"}, input_html:{class:"input-bakery-description"}, placeholder:"..." %>

    </div>


    <div class="pictures">
      <%= f.input :pictures, as: :file, label_html:{ class:"file-btn-label"},  input_html: { class:"input-bakery-pictures", multiple: true } %>
    </div>
    <div class="button-submit-form">
      <%= f.submit " Create a bakery ", class: "style-btn-form" %>
    </div>
  <% end %>
</div>
<!-- add specialty and tags-->

app/views/bakeries/show.html.erb
<div class='show-container pt-2 d-flex '>
  <div>
    <div class="picture-bakery">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner" style="margin: 0px; padding: 0px; border: 0px; margin: none; ">
            <%unless @bakery.pictures.attached? %>
            <div class="carousel-item active">
              <img class="d-block w-100" src="https://placeimg.com/500/500/animals" alt="First slide" style=" margin: none; padding: none;">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://placeimg.com/500/500/arch" alt="Second slide" style=" margin: none; padding: none;">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://placeimg.com/500/500/nature" alt="Third slide" style=" margin: none; padding: none;">
            </div>
            <% else %>
            <div class="carousel-item active">
                <img class="d-block w-100" src=<%= cl_image_path @bakery.pictures.first.key ,height: 300, width: 300, crop: :fill  %> alt="First slide" style="min-width:100%; margin: none; padding: none;object-fit: fill;">
              </div>
              <% @bakery.pictures[1..-1].each do |picture|%>
              <div class="carousel-item">
                <img class="d-block w-100" src=<%= cl_image_path picture.key ,height: 300, width: 300, crop: :fill  %> alt="First slide" style="min-width:100%; margin: none; padding: none; object-fit: fill;">
              </div>
              <%end %>
              <div class="carousel-item">
              <img class="d-block w-100" src="https://deliciousmagazine.nl/app/uploads/2021/01/pastel-de-nata-1024x683.jpg" style="min-width:100%; margin: none; padding: none;object-fit: fill;">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://www.lbpbakeries.com/wp-content/uploads/2020/11/67460-pack-scaled.jpg" style="min-width:100%; margin: none; padding: none;object-fit: fill;">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_2x/public/2020-02/the-easiest-loaf-of-bread-youll-ever-bake.jpg?itok=LsBnSw0g" alt="Third slide" style="min-width:100%; margin: none; padding: none;object-fit: fill;">
            </div>
            <%end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

    </div>

    <div class='average-rating'>
      <div class='d-flex total-visitors'>
        <p class='visitors'>Visitors:   <%= @visitors.empty? ? 0 : @visitors.length %><%= image_tag "person-solid.svg", class:"person-icon" %></p>
        <p class='total'>Total reviews:   <%= @bakery.reviews.count unless @bakery.reviews.empty? %><%= image_tag "person-solid.svg", class:"person-icon" %> </p>
      </div>
      <p class='locals'>Locals: <%= @locals.empty? ? 0 : @locals.length%> <%= image_tag "person-solid.svg", class:"person-icon" %></p>
      <% if @bakery.average_rating %>
        <p class='average'>Average rating:   <%@bakery.average_rating.to_i.times do %>
          <i class="fas fa-star"></i>
        <%end %></p>
      <%end %>
    </div>

  </div>

  <div class='content'>
    <div class="bakery-description ">
      <div class='d-flex justify-content-between'>
        <div class="info">
          <div class="show_bakery_name">
            <h4><%=@bakery.name.upcase%></h4>
          </div>
          <div class="ranking-div">
            <p class= 'ranking'><%= "##{@bakery.rank.to_i + 1} IN BELGIUM" %></p>
          </div>
          <div class=" show show_address">
            <%= @bakery.address.capitalize %>, <%= @bakery.post_code %>
          </div>
          <div class="show phone">
            <%= @bakery.phone_number %>
          </div>

        </div>



          <div class='schedule p-2 d-flex justify-content-between'>
            <div>
              <div class='favourites-show' data-controller="refresh-list">
                <%= render '/bakeries/favourites', bakery: @bakery, class: "favourites" %>
              </div>

              <div>
                <p class='m-0'>Opening hour</p>
                <p class='hour_icon'><%= @bakery.opening_hour.strftime("%H:%M") %></p>
              </div>
              <div>
                <p class=' mt-2 m-0'>Closing hour</p>
                <p class='hour_icon'><%= @bakery.closing_hour.strftime("%H:%M") %></p>
              </div>
              <div>
                <% if (Time.now.hour > @bakery.opening_hour.hour && Time.now.hour < @bakery.closing_hour.hour)%>
                  <p style="color:green ; text-align:center">Open now</p>
                <%else %>
                  <p class="open-closed" style="color:red">Closed now</p>
                <%end %>
              </div>
            </div>
          <div></div></div>


      </div>
      <div id="text" class='d-flex pt-2'>
        <div class='description-tags' data-controller="create-tags">
          <div class='d-flex'  data-create-tags-target='tags'>
            <% if @bakery.tags.empty? %>
              <div class='show-tag'>
                <a class='btn'>Vegan</a>
              </div>
              <div class='show-tag'>
                <a class='btn'>Cheap</a>
              </div>
            <%else %>
              <% @bakery.tags.each do |tag| %>
                <%= render 'tag', tag: tag %>
              <%end %>
            <% end %>
          </div>
          <div class='create-tag'>
              <button class='new-tag-btn show-tag'data-action="click->create-tags#displayForm"><i class=" fas fa-pen fa-xs ml-2" ></i> Add new Tag</button>

              <div class="tag-form">
                <%= simple_form_for [@bakery, @tag], method: :post, html: { class:'new-tag-form d-none', data: { create_tags_target: 'form', action: 'submit->create-tags#create'  } } do |f| %>
                    <%= f.input :category, input_html: { class: "tag-input" } %>

                    <%= f.submit "", :class => "button_with_image_save"  %>

                  <%end %>
              </div>

          </div>


          <p class='show'><%= @bakery.description %></p>

        </div>

      </div>
      <div class='d-flex products' >
        <div class="must-try-bakery" style="width:200px;">
          <p style="font-size: 25px;padding-right:10px">MUST TRY!</p>

          <div id="specialty-bakery" style='margin-top:10px; margin-left:20px;'>
            <% @speciality.each do |special|%>
                <div class='spe' style="padding-right:20px" ><% unless @speciality.empty? %><%=  special.name %></div>
              <%end  %>
            <%end %>
          </div>
        </div>
        <div class="menu-bakery" style="width:200px;">
          <p style="font-size: 25px;padding-right:10px">MENU</p>

          <div id="me" style='margin-top:30px; margin-left:20px;'>
            <%unless @products.empty? %>
              <% @products.each do |product|%>
                <span class='show ml-2' style="padding-right:20px"><%=  product.name%></span>
              <%end  %>
            <%end %>
          </div>
        </div>
      </div>

        <div class="div-btn-go">
          <button class="learn-more">
            <span class="circle" aria-hidden="true">
              <span class="icon arrow"></span>
            </span>
            <a href='#map' class="button-text">GO THERE</a>
          </button>
        </div>
    </div>

  </div>

</div></div></div>

<div class='show-container show-reviews'data-controller="create-reviews">
  <div class='container-new-tag'>
    <div >
    <button class='new-review show-tag'data-action="click->create-reviews#displayForm"><i class="fas fa-pen fa-xs ml-2" ></i>
      create a review</button>
      <%= simple_form_for [@bakery,@review], method: :post, html: { class:'d-none',style:"width: 30%; margin: auto;", data: { create_reviews_target: 'form', action: 'submit->create-reviews#create'  } } do |f| %>
      <%=f.input :title %>
       <%= f.input :content,  html: { class:'content', style:"width: 30%; margin: 0px;"} %>
      <%=f.input :rating ,as:
            :select,
            collection: [['1',1],['2',2],['3',3],['4',4],['5',5]],
            disabled: [] ,
            label: 'Add a rating to your review' %>
      <%= f.input :photo, as: :file ,
                  label: 'Add a picture to your review'%>

      <%=f.input :visitor,
            label: 'Local/visitor',
            as: :select,
            collection: [['local',false],['visitor',true]],
            disabled: [] %>
      <%= f.submit %>
    <%end %>
    </div>
  </div>
      <div data-create-reviews-target='reviews'>
      <% if @bakery.reviews.count > 4 %>
              <%@bakery.reviews.reverse[0..4].each do |review| %>
                <%= render '/reviews/reviews', review: review%>
                <%end %>
              <%elsif @bakery.reviews.count >0%>
                <%@bakery.reviews.reverse.each do |review| %>
                  <%= render '/reviews/reviews', review: review %>
                <%end %>
              <%end %>
      </div>
  <!-- Below is the right column with the map -->

    <div class="map-show mb-3 " id="map"
        style=" height: 92vh; width:93.5vw;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

</div>