config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :bakeries do
    resources :reviews, only: [:new, :create]
    resources :tags, only: [:new, :create, :update]
  end
  get 'bakeries/addtofav/:id', to: "bakeries#update_favourites"

  resources :users
  get 'users/:id/favourites', to: "users#favourites"
  resources :favourites
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bakery.rb
class Bakery < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :tags, dependent: :destroy
  belongs_to :user
  has_many_attached :pictures
  geocoded_by :address
  after_validation :geocode

  include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [ :name],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :bakery

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :bakery
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :bakery
  has_one_attached :photo
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :bakery
  has_many :user_tags, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bakeries, dependent: :destroy
  has_many :user_tags, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favourites, dependent: :destroy
end

app/models/user_tag.rb
class UserTag < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @bakeries = current_user.favourites.map{|fav| fav.bakery}
    test = Bakery.where(id: @bakeries.pluck(:id))
    @markers = test.geocoded.map do |bakery|
      {
        lat: bakery.latitude,
        lng: bakery.longitude,
        image_url: helpers.asset_url('baguette2.png'),
        info_window: render_to_string(partial: "../views//bakeries/info_window", locals: { bakery: bakery })
      }
    end

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end
  def create
    @bakery = Bakery.find(params[:bakery_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.bakery = @bakery
    if @review.save
      respond_to do |format|
      format.html { redirect_to bakery_path(@bakery) }
      format.text { render partial: 'reviews/reviews', locals: { review: @review }, formats: [:html] }
      end
    end
  end
  private

def review_params
  params.require(:review).permit(:content, :title,:visitor,:rating,:photo)
end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
   skip_before_action :verify_authenticity_token, :only => [:update]

  def new
      @tag = Tag.new
  end
  def create
    @bakery = Bakery.find(params[:bakery_id])
    @tag = Tag.new(tag_params)
    @tag.bakery = @bakery
    @user_tag = UserTag.create(user: current_user, tag: @tag)
    if (@tag.save && @user_tag.save)
      respond_to do |format|
      format.html { redirect_to bakery_path(@bakery) }
      format.text { render partial: 'bakeries/tag', locals: { tag: @tag }, formats: [:html] }
      end
    end
  end

  def update
    @bakery = Bakery.find(params[:bakery_id])
    @tag = Tag.find(params[:id])
    @verify_user_tag = UserTag.where(tag: @tag).where(user: current_user)
    if @verify_user_tag.empty?
      @user_tag = UserTag.new(user: current_user, tag: @tag)
      if @user_tag.save
        respond_to do |format|
          format.html { redirect_to bakery_path(@bakery) }
          format.text { render partial: 'bakeries/tag', locals: { tag: @tag }, formats: [:html] }
        end
      end
    else
      respond_to do |format|
          format.html { redirect_to bakery_path(@bakery) }
          format.text { render partial: 'bakeries/tag', locals: { tag: @tag }, formats: [:html] }
        end

    end
  end

  private

  def tag_params
    params.require(:tag).permit(:category)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @favourites = Favourite.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if params[:controller] == "pages" && params[:action] == "home" %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon home-navbar">

<% else%>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
<% end %>

  <% unless current_page?(root_path) %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

      <div class="logo">
        <%= link_to "/", class: "navbar-brand" do %>
          <%= image_tag "logo-bbe.png", class:"logo-bbe" %>
        <% end %>
      </div>

    <div class='search-bar'>
      <%= form_tag bakeries_path, method: :get do %>
        <div class="col-sm d-flex column justify-content-center">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            id: "search-form-control",
            placeholder: "Find a bakery"
          %>

          <button name="button" type="submit" class="btn search_button_nav">
            <i class="fas fa-search"></i>
          </button>
        </div>
      <% end %>
    </div>
  <% end %>


  <div class="dropdown">

	  <div class="btn-menu dropdown-toggle" type="button" id="dropdownMenuButton1" data-toggle="dropdown" aria-expanded="false">
      <%= image_tag "menu_icon.png", class:"menu-bbe" %>
    </div>

	  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
      <%unless current_user %>
        <li><%= link_to "Log in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      <%else %>
        <li><%= link_to "All bakeries", bakeries_path, method: :get %></li>
        <div class="dropdown-divider"></div>
        <li><%= link_to "My favourites", favourites_path%></li>
        <div class="dropdown-divider"></div>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>


      <% end %>

       <!--
        <li><a class="dropdown-item" href="">Account</a></li>
        <li><a class="dropdown-item" href="#">Favourites</a></li>
        -->
	  </ul>
	</div>

  <!--closind div-->
</div>